server:
  port: 8081
spring:
  application:
    name: cloud-mall-user
  datasource:
    name: flagship_mall_datasource
    url: jdbc:mysql://localhost:3306/flagship_mall?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint}
                   %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint}
                   %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
mybatis:
  mapper-locations: classpath:mappers/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
